#!/usr/bin/env python3
"""
generate_cwe_js.py
Converts a CWE XML catalog (cwec_vX.Y.Z.xml) to data/cwe.js.

Usage:
    python generate_cwe_js.py                          # auto-detects cwec_*.xml in current dir
    python generate_cwe_js.py cwec_v4.19.1.xml
    python generate_cwe_js.py wec.xml --out cwe.js

Output format (window._CWE_DB):
    { "ID": { "n": "Name", "d": "Description", "c": ["CAPEC_ID",...], "p": "ParentID"|null }, ... }
    p = primary parent in CWE View 1000 (Research Concepts), null for root nodes.
"""

import argparse
import glob
import json
import os
import sys
import xml.etree.ElementTree as ET

NS = "http://cwe.mitre.org/cwe-7"


def find_xml() -> str:
    """Auto-detect cwec_*.xml in the current directory."""
    matches = glob.glob("cwec_*.xml") + glob.glob("*.xml")
    if not matches:
        sys.exit("No CWE XML file found. Pass the path explicitly.")
    if len(matches) > 1:
        print(f"Multiple XML files found, using: {matches[0]}", file=sys.stderr)
    return matches[0]


def parse(xml_path: str) -> dict:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    tag_weakness = f"{{{NS}}}Weakness"
    tag_desc     = f"{{{NS}}}Description"
    tag_rws      = f"{{{NS}}}Related_Weaknesses"
    tag_rw       = f"{{{NS}}}Related_Weakness"
    tag_raps     = f"{{{NS}}}Related_Attack_Patterns"

    weaknesses_el = root.find(f"{{{NS}}}Weaknesses")
    if weaknesses_el is None:
        weaknesses_el = root.find("Weaknesses")
    if weaknesses_el is None:
        sys.exit("Could not find <Weaknesses> element in the XML.")

    # First pass: build primary-parent map (View 1000, Nature=ChildOf, Ordinal=Primary)
    parent_map = {}
    for w in weaknesses_el:
        if w.tag not in (tag_weakness, "Weakness"):
            continue
        wid = w.get("ID", "")
        rws_el = w.find(tag_rws)
        if rws_el is None:
            rws_el = w.find("Related_Weaknesses")
        if rws_el is None:
            continue
        for r in rws_el:
            if (r.get("Nature") == "ChildOf"
                    and r.get("View_ID") == "1000"
                    and r.get("Ordinal") == "Primary"):
                parent_map[wid] = r.get("CWE_ID")
                break

    # Second pass: build full DB
    db = {}
    for w in weaknesses_el:
        if w.tag not in (tag_weakness, "Weakness"):
            continue
        wid  = w.get("ID", "")
        name = w.get("Name", "")

        desc_el = w.find(tag_desc)
        if desc_el is None:
            desc_el = w.find("Description")
        desc = (desc_el.text or "").strip() if desc_el is not None else ""

        raps_el = w.find(tag_raps)
        if raps_el is None:
            raps_el = w.find("Related_Attack_Patterns")
        capecs = []
        if raps_el is not None:
            for r in raps_el:
                cid = r.get("CAPEC_ID")
                if cid:
                    capecs.append(cid)

        db[wid] = {"n": name, "d": desc, "c": capecs, "p": parent_map.get(wid)}

    return db


def main():
    parser = argparse.ArgumentParser(description="Convert CWE XML to cwe.js")
    parser.add_argument("xml", nargs="?", help="Path to cwec_*.xml (auto-detected if omitted)")
    parser.add_argument("--out", default=os.path.join("cwe.js"),
                        help="Output path (default: data/cwe.js)")
    args = parser.parse_args()

    xml_path = args.xml or find_xml()
    if not os.path.isfile(xml_path):
        sys.exit(f"File not found: {xml_path}")

    print(f"Parsing {xml_path} …")
    db = parse(xml_path)

    basename    = os.path.basename(xml_path)
    version     = basename.split("_v", 1)[1].replace(".xml", "") if "_v" in basename else ""
    with_capec  = sum(1 for e in db.values() if e["c"])
    with_parent = sum(1 for e in db.values() if e["p"])
    print(f"  {len(db)} weaknesses | {with_parent} with parent (view 1000) | {with_capec} with CAPEC links")

    payload = json.dumps(db, separators=(",", ":"), ensure_ascii=False)
    header  = f"/* CWE DB v{version} — auto-generated by generate_cwe_js.py, do not edit */\n"
    js      = header + f"window._CWE_DB={payload};"

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Written to {args.out} ({len(js.encode()) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()